// vue-app/src/components/TryOnCanvas.vue
<script setup>
import { ref, onMounted, onUnmounted, watch } from 'vue'
import { TryOnEngine } from '../../../core/engine.js'

const props = defineProps({
  videoRef: { type: Object, required: true },
})

const emit = defineEmits(['engine-ready'])

const containerRef = ref(null)
let engine = null
let frameInterval = null
let offscreen = null

function startFrameSender() {
  const canvas = document.createElement('canvas')
  canvas.width = 320
  canvas.height = 240
  offscreen = canvas

  const send = () => {
    if (!props.videoRef || props.videoRef.readyState < 2) return
    const ctx = canvas.getContext('2d')
    ctx.drawImage(props.videoRef, 0, 0, 320, 240)
    engine?.sendFrameToServer(canvas)
  }

  send()
  frameInterval = setInterval(send, 300)
}

async function initEngine() {
  if (!containerRef.value || !props.videoRef) return

  engine = new TryOnEngine()
  emit('engine-ready', engine)

  await engine.initScene(props.videoRef, containerRef.value)
  await engine.initMediaPipe()

  engine.connectWebSocket()
  startFrameSender()

  engine.startTracking()
}

onMounted(() => {
  initEngine()
})

onUnmounted(() => {
  if (frameInterval) clearInterval(frameInterval)
  engine?.dispose()
})

watch(() => props.videoRef, () => {
  if (props.videoRef) initEngine()
})
</script>

<template>
  <div
    ref="containerRef"
    class="tryon-container"
  />
</template>

<style scoped>
.tryon-container {
  position: absolute;
  inset: 0;
  z-index: 2;
}
</style>

// next-app/components/TryOnCanvas.jsx
'use client'

import { useRef, useEffect, useCallback } from 'react'
import { TryOnEngine } from '../../core/engine.js'

export default function TryOnCanvas({ videoRef, cameraReady, onEngineReady }) {
  const containerRef = useRef(null)
  const engineRef = useRef(null)
  const frameIntervalRef = useRef(null)
  const offscreenRef = useRef(null)

  const startFrameSender = useCallback((engine) => {
    const canvas = document.createElement('canvas')
    canvas.width = 320
    canvas.height = 240
    offscreenRef.current = canvas

    const send = () => {
      if (!videoRef.current || videoRef.current.readyState < 2) return
      const ctx = canvas.getContext('2d')
      ctx.drawImage(videoRef.current, 0, 0, 320, 240)
      engine.sendFrameToServer(canvas)
    }

    send()
    frameIntervalRef.current = setInterval(send, 300)
  }, [videoRef])

  const initEngine = useCallback(async () => {
    if (!containerRef.current || !videoRef.current) return

    const engine = new TryOnEngine()
    engineRef.current = engine
    onEngineReady(engine)

    await engine.initScene(videoRef.current, containerRef.current)
    await engine.initMediaPipe()

    engine.connectWebSocket()
    startFrameSender(engine)

    engine.startTracking()
  }, [videoRef, onEngineReady, startFrameSender])

  useEffect(() => {
    if (cameraReady && containerRef.current) {
      initEngine()
    }
    return () => {
      if (frameIntervalRef.current) clearInterval(frameIntervalRef.current)
      engineRef.current?.dispose()
    }
  }, [cameraReady, initEngine])

  return (
    <div
      ref={containerRef}
      style={{
        position: 'absolute',
        inset: 0,
        zIndex: 2,
      }}
    />
  )
}
